import { FrameState } from '@/app/store/use-editor-store';

export const frames = [
  {
    id: 'hello world',
    texts: [
      {
        text: 'Hello World',
        fontSize: 16,
        color: '#000',
        backgroundColor: '#ffffff',
        fontFamily: 'string',
        fontWeight: '400',
        colorType: 'solid',
        x: '50%',
        y: '50%',
      },
      {
        text: 'Hello World22',
        fontSize: 16,
        color: '#000',
        backgroundColor: '#ffffff',
        fontFamily: 'string',
        fontWeight: '400',
        colorType: 'solid',
        x: '10%',
        y: '10%',
      },
    ],
    emojis: [],
    duration: 1200,
    backgroundType: 'solid',
    backgroundColor: '#ffffff',
  },
  {
    id: 'hello world 2',
    texts: [
      {
        text: 'Hello World 2',
        fontSize: 16,
        color: '#000',
        backgroundColor: '#ffffff',
        fontFamily: 'string',
        fontWeight: '400',
        colorType: 'solid',
        x: '50%',
        y: '50%',
      },
    ],
    emojis: [],
    duration: 1300,
    backgroundType: 'solid',
    backgroundColor: '#ffffff',
  },
  {
    id: 'hello world3',
    texts: [
      {
        text: 'Hello World 3',
        fontSize: 16,
        color: '#000',
        backgroundColor: '#ffffff',
        fontFamily: 'string',
        fontWeight: '400',
        colorType: 'solid',
        x: '50%',
        y: '50%',
      },
    ],
    emojis: [],
    duration: 500,
    backgroundType: 'solid',
    backgroundColor: '#ffffff',
  },
  {
    id: 'hello world4',

    texts: [
      {
        text: 'Hello World 4',
        fontSize: 16,
        color: '#000',
        backgroundColor: '#ffffff',
        fontFamily: 'string',
        fontWeight: '400',
        colorType: 'solid',
        x: '50%',
        y: '50%',
      },
    ],
    emojis: [],
    duration: 600,
    backgroundType: 'solid',
    backgroundColor: '#ffffff',
  },
  {
    id: 'hello world5',

    texts: [
      {
        text: 'Hello World 5',
        fontSize: 16,
        color: '#000',
        backgroundColor: '#ffffff',
        fontFamily: 'string',
        fontWeight: '400',
        colorType: 'solid',
        x: '50%',
        y: '50%',
      },
    ],
    emojis: [],
    duration: 1000,
    backgroundType: 'solid',
    backgroundColor: '#ffffff',
  },
  {
    id: 'hello world7',

    texts: [
      {
        text: 'Hello World 6',
        fontSize: 16,
        color: '#000',
        backgroundColor: '#ffffff',
        fontFamily: 'string',
        fontWeight: '400',
        colorType: 'solid',
        x: '50%',
        y: '50%',
      },
    ],
    emojis: [],
    duration: 1200,
    backgroundType: 'solid',
    backgroundColor: '#ffffff',
  },
] as FrameState[];
